library(dtlng)

dtf <- data.frame(A = c(1,2,3), B = c(2,3,4), C = c(3,4,5))
dfi1 <- asDfi(dtf)
dfi2 <- dfi1 %>% select_("A", "C")
dfi3 <- dfi1 %>% select_("A", "C") %>% select_("C")
dfi4 <- dfi2 %>% select_("C")
dfi5 <- asDfi(data.frame(AAA = c(1,2,3), Z = c(1,2,3)))
dfi6 <- dfi1 %>% full_join(dfi5, by = c("A" = "AAA"))
dfi7 <- dfi6 %>% select_("B", "C", "Z") %>% full_join(dfi2, by = c("C"))
